### ISSUE TITLE
(RSS-)Feed anbieten

### ISSUE THREAD

**Issue by aCandidMind** [coderbyheart/ugrm#10]
Hallo,

zuerst mal vielen Dank für die Arbeit, die du in unsere Region steckst ;-)

Cool wäre aber noch, wenn es die Möglichkeit gäbe, einen Feed zu abonnieren. Oder habe ich da etwas blindlings übersehen?

Kann natürlich auch sein, dass du die Leute zum Seitenaufruf motivieren willst, spricht ja nichts dagegen. Auf der anderen Seite, kannst du ja auch verkürzte Informationen im feed haben und auf der Seite sind dann die ausführlichen Informationen.

Wenn die Seite in Rails geschrieben wäre, hätte ich evtl. mithelfen können, aber PHP fass' ich nicht an ;-)

Beste Grüße

**Comment by coderbyheart** [comment]
Der http://usergroups.rheinmainrocks.de/todayfeed enthält die heute statt findenden Events.

**Comment by t-8ch** [comment]
@coderbyheart Danke für den nativen iCal support!
Könntest du noch ical feeds für spezifische Gruppen implementieren?
