### ISSUE TITLE
Export events in iCalendar format

### ISSUE THREAD

**Issue by t-8ch** [coderbyheart/ugrm#3]
It would be nice to be able to subscribe to the events of a subset of the user groups.

`http://usergroups.rheinmainrocks.de/calendar/` subscribes to all groups
`http://usergroups.rheinmainrocks.de/calendar/?filter=ccczmwi,jugf` only exports those two groups.

**Comment by coderbyheart** [comment]
This has landed in core: http://usergroups.rheinmainrocks.de/ical
